In [1]:
import numpy as np

In [2]:
ar = np.array([[1,2,3],[4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# ar.dtype
# ar.size #6
ar.shape

(2, 3)

In [4]:
# ars = np.array([3,6,36777,8],np.int8)
# ars #array([  3,   6, -87,   8], dtype=int8)

ars = np.array([3,6,36777,8],np.int32)
ars #array([    3,     6, 36777,     8], dtype=int32)



array([    3,     6, 36777,     8], dtype=int32)

In [5]:
np.array({3,4,5})
#array({3, 4, 5}, dtype=object)
#not sufficetn everytime

array({3, 4, 5}, dtype=object)

In [6]:
li =[[1,2,3],[4,5,6]]
arr=np.array(li)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
zero =np.zeros((2,3))
zero

# arrr = np.zeros([2,3])
# arrr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
ae = np.ones([5,])
ae

array([1., 1., 1., 1., 1.])

In [9]:
asss = np.arange(10)
asss
# asss.reshape(3,2) 
# asss = asss.reshape(3,2)
# ad = np.arange(1,11,2)
# ad

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
asss = np.arange(2,3)
asss #array([2])


# ad = np.arange(1,11,2)
# ad

array([2])

In [11]:
an = np.random.rand(3,3)
an

array([[0.87310568, 0.51862476, 0.69365902],
       [0.65160915, 0.37098528, 0.89129842],
       [0.92409906, 0.30608639, 0.79784505]])

In [12]:
am = np.arange(9).reshape((3,3))

am

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_3 = arr[:, 2]
# max_3 = np.argmax(col_3)
# col_3[max_3]
# max_3

maxx = np.max(col_3)
maxx

6

In [14]:
2**10

1024

In [15]:
a = np.linspace(1,100,1024)
n=a.reshape(2,2,2,2,2,2,2,2,2,2)
n.ndim

10

In [16]:
emp = np.empty((4,6))
emp

array([[4.64753580e-310, 0.00000000e+000, 2.34544040e+251,
        2.72157657e+257, 3.77268046e+233, 2.68047312e-260],
       [1.87719729e-009, 7.16395186e-322, 6.93945788e-310,
        6.93945788e-310, 1.87725413e-009, 5.03128776e+180],
       [5.98117523e-114, 8.78940355e+252, 2.43905614e-154,
        4.29058029e+270, 5.22923643e-067, 1.36545436e-071],
       [7.01413727e-009, 4.91461491e+252, 5.29345021e+180,
        5.98181709e-154, 2.42767533e-154, 1.04019395e-317]])

In [17]:
emp_like = np.empty_like(emp)
emp_like

array([[4.64753580e-310, 0.00000000e+000, 2.34544040e+251,
        2.72157657e+257, 3.77268046e+233, 2.68047312e-260],
       [1.87719729e-009, 7.16395186e-322, 6.93945788e-310,
        6.93945788e-310, 1.87725413e-009, 5.03128776e+180],
       [5.98117523e-114, 8.78940355e+252, 2.43905614e-154,
        4.29058029e+270, 5.22923643e-067, 1.36545436e-071],
       [7.01413727e-009, 4.91461491e+252, 5.29345021e+180,
        5.98181709e-154, 2.42767533e-154, 1.04019395e-317]])

In [18]:
ide = np.identity(8)
ide
# ide.shape #(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
ide.ravel() #ide will be converted into one Dim array

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [21]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [25]:
ar.sum(axis=0) #col -array([12,  8,  9])
# ar.sum(axis=1) #row -array([ 6, 15,  8])


array([12,  8,  9])

In [26]:
ar.T #transpose-row to col

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [27]:
for item in ar.flat:
    print(item)
#  will prinall the items 

1
2
3
4
5
6
7
1
0


In [28]:
ar.ndim #dimention

2

In [29]:
ar.size #total ele

9

In [30]:
ar.nbytes

72

In [37]:
one = np.array([1,3,4,634,2])
one.argmax() #will return the index of the max ele
one.argmin()
one.argsort() #will return the index of the sorted array


array([0, 4, 1, 2, 3])

In [41]:
ar.argmin() #8 - 8th index was the min ele
ar.argmax()
ar.argmax(axis=0) #will give ma of every col
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar2 = np.array([[1,2,1],[4,5,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 5, 6],
       [8, 1, 0]])

In [45]:
ar + ar2 
#if we try to add 2 li it will just append but here numpy array wont append but just perform the operation

array([[ 2,  4,  4],
       [ 8, 10, 12],
       [15,  2,  0]])

In [46]:
ar * ar2

array([[ 1,  4,  3],
       [16, 25, 36],
       [56,  1,  0]])

In [48]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [49]:
ar.sum()
ar.min()
ar.max()

7

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
np.where(ar>5)
# type(np.where(ar>5))
# (array([1, 2]), array([2, 0]))
#  here it is stored as tuple and 1,2 is the index pos,1st row adn 2nd col

(array([1, 2]), array([2, 0]))

In [56]:
np.count_nonzero(ar)

8

In [57]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [65]:
 ar[1,2]=0

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [67]:
import sys

In [78]:
py_ar = [0,4,55,2]
np_ar = np.array(py_ar,np.int32)


In [79]:
sys.getsizeof(1) * len(py_ar)

112

In [80]:
np_ar.itemsize * np_ar.size

16

In [82]:
ar[0,-1]

3

In [84]:
np_ar.tolist() #list

[0, 4, 55, 2]